GET http://localhost:5000/api/user HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ2M2Y2YWZhLWQ3Y2UtNDVkMi04YjRkLWIyZGY2MGE3ODBjNSIsImVtYWlsIjoidGVzdEBtYWlsLmNvbSIsInJvbGVzIjpbIlVTRVIiXSwiaWF0IjoxNzA3OTg5NzEyLCJleHAiOjE3MDgwNzYxMTJ9.v4exTZ8WsFjwnWrXFRIYI5F-cYI9RSKX6rO6VREs6tA
###
POST http://localhost:5000/api/user/currentUser HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYTBlOWUxLWUyN2UtNGU1Ny1iMWQ3LTdhNzliNmNmYTcwYyIsImVtYWlsIjoidGVuZGVyNjc5NTExMUBnbWFpbC5jb20iLCJyb2xlcyI6WyJVU0VSIl0sImlhdCI6MTcwNzgxMTI4OSwiZXhwIjoxNzA3ODk3Njg5fQ.hdNTj6fZ5P9U1E82dj8mE1a81LbT-siJcmpkgTCek2I
###

GET http://localhost:5000/api/user/teamleaders/false HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJkNTc4Yjc1LWZhZWYtNDQ3My04OWU4LTg3ZmM5YzgxYWJhMiIsImVtYWlsIjoidGVzdEBnbWFpbC5jb20iLCJyb2xlcyI6WyJERVZFTE9QRVIiLCJURUFNTEVBREVSIl0sImZpcnN0TmFtZSI6ItCS0LXQu9C40LrQuNC5IiwibGFzdE5hbWUiOiLQmtC-0LzQv9GM0Y7RgtC10YDRidC40JoiLCJpYXQiOjE3MjQ0MDIwOTMsImV4cCI6MTcyNDQ4ODQ5M30.UuXrUQ8FVAU70CsEmtNl6fDimjmE3u4nLtfN2wAZu0c
###
GET http://localhost:5000/api/user/workers HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJkNTc4Yjc1LWZhZWYtNDQ3My04OWU4LTg3ZmM5YzgxYWJhMiIsImVtYWlsIjoidGVzdEBnbWFpbC5jb20iLCJyb2xlcyI6WyJERVZFTE9QRVIiLCJURUFNTEVBREVSIl0sImZpcnN0TmFtZSI6ItCS0LXQu9C40LrQuNC5IiwibGFzdE5hbWUiOiLQmtC-0LzQv9GM0Y7RgtC10YDRidC40JoiLCJpYXQiOjE3MjU0NTY0NzcsImV4cCI6MTcyNTU0Mjg3N30.SARRf3a5GweGaEX-_MU5wIQJU6FkPi_pzgQ8OyQrCWc
###
PATCH  http://localhost:5000/api/user/updateUserMultiple HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJkNTc4Yjc1LWZhZWYtNDQ3My04OWU4LTg3ZmM5YzgxYWJhMiIsImVtYWlsIjoidGVzdEBnbWFpbC5jb20iLCJyb2xlcyI6WyJERVZFTE9QRVIiLCJURUFNTEVBREVSIl0sImZpcnN0TmFtZSI6ItCS0LXQu9C40LrQuNC5IiwibGFzdE5hbWUiOiLQmtC-0LzQv9GM0Y7RgtC10YDRidC40JoiLCJpYXQiOjE3MjUzNjg5MTcsImV4cCI6MTcyNTQ1NTMxN30.v756hrbQf6xnQvsPrAjLl60Dt6CAveJhCQrTU4BJulY

[{
    "id":"8504ea46-6a9f-4910-bc9e-1560a671a973",
    "teamId": "8966e2c9-bfd7-40ed-9a53-be5b78e2c200"
}]