version: "3"

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: janedoe
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: edu_tech
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXP: ${JWT_EXP}

  nextjs:
    build: ../edu_tech 
    ports:
      - "3000:3000"
    depends_on:
      - app
    environment:
      NODE_ENV: development  
    command: npm run dev
    volumes:
    - ../edu_tech:/app

volumes:
  postgres_data: