services:
  postgres:
    image: postgres:14
    networks:
      - network
    environment:
      POSTGRES_USER: janedoe
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: edu_tech
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
#      network: host
    ports:
      - "5000:5000"
    networks:
      - network
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXP: ${JWT_EXP}

  nextjs:
    build: ../edu_tech
#      network: host
    ports:
      - "3000:3000"
    networks:
      - network
    depends_on:
      - app
    environment:
      NODE_ENV: development
    command: npm run dev
    volumes:
    - ../edu_tech:/app

networks:
  network:
    driver: bridge

volumes:
  postgres_data:
